linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - unused
linters-settings:
  errcheck:
    exclude-functions:
      - golang.org/x/term.Restore
