version: 2
project_name: pijoy
builds:
  - id: console
    main: ./cmd/console
    no_unique_dist_dir: true
    binary: pizero/console
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/sweatybridge/pijoy/internal.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
  - id: debug
    main: ./cmd/debug
    no_unique_dist_dir: true
    binary: pizero/debug
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/sweatybridge/pijoy/internal.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
  - id: joystick
    main: ./cmd/joystick
    no_unique_dist_dir: true
    binary: pizero/joystick
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/sweatybridge/pijoy/internal.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
release:
  draft: true
  replace_existing_draft: true
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
