// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package api

// Defines values for Button.
const (
	Down  Button = "down"
	Left  Button = "left"
	Right Button = "right"
	Up    Button = "up"
)

// Defines values for HealthStatus.
const (
	Draining HealthStatus = "draining"
	Ready    HealthStatus = "ready"
)

// Button defines model for Button.
type Button string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// InternalError defines model for InternalError.
type InternalError = Error
