name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - run: |
          go run gotest.tools/gotestsum -- ./... -race -v -count=1 \
          -coverpkg ./internal/... -coverprofile=coverage.out

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          # Linter requires no cache
          cache: false

      - uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 3m --verbose

  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - run: go generate cmd/joystick/main.go
      - run: |
          if ! git diff --ignore-space-at-eol --exit-code --quiet internal/api; then
            echo "Detected uncommitted changes after codegen. See status below:"
            git diff
            exit 1
          fi
